%YAML 1.2
---
#--------------------#
# general parameters #
#--------------------#

# prefix for output files
out: "bulk"

# how much debug output should be printed to screen? (1: lowest)
verbosity: 1

# random seed
seed: 123456789


#-----------------------#
# clone tree parameters #
#-----------------------#

# user-provided clone tree (overrides parameters below)
tree: "data/bulk/bulk.tre"

# number of clones to simulate
clones: 5
# number of total mutations to simulate
mutations: 10000
# number of transforming mutations shared by all clones
# (included in total mutations)
init-muts: 100

#----------------------------#
# existing seq data as input #
#----------------------------#

# setting this property deactivates simulation of
## 1. reference genome
## 2. reference reads
## 3. germline mutations
#bam-input: crc.ref.sam
# file containing reference genome sequence
#reference: data/ref/Hg18.chr20-22.fa
#chr0-335294

#-------------------------#
# reference genome params #
#-------------------------#

# parameters to generate reference genome
## number of sequences (e.g. chromosomes) to generate
ref-seq-num: 10
## sequence length
ref-seq-len-mean: 100000
ref-seq-len-sd: 10000
## nucleotide frequencies (ACGT)
ref-nuc-freqs: [ 0.3, 0.2, 0.2, 0.3 ]

#-------------------------------#
# germline evolution parameters #
#-------------------------------#

# germline variants (to generate personal genome from reference)
#reference-vcf: data/input/1000G_phase1.indels.b37.vcf
mut-germline : 1000

# evolutionary model
# choices: 'JC', 'F81', 'K80', 'HKY', 'matrix', 'matrixFromVcf'
model: matrix
model-params:
  # nucleotide frequencies:
  nucFreq : [ 0.25, 0.25, 0.25, 0.25 ]
  # transition-transversion ratio:
  kappa   : 1
  # custom nucleotide substitution matrix (ACGT):
  Qa      : [    0.0, 0.0406, 0.1661, 0.0331 ]
  Qc      : [ 0.0417,    0.0, 0.0438, 0.1746 ]
  Qg      : [ 0.1744, 0.0440,    0.0, 0.0418 ]
  Qt      : [ 0.0331, 0.1662, 0.0405,    0.0 ]

#------------------------------#
# somatic evolution parameters #
#------------------------------#

# somatic variants file
mut-som-vcf: crc.somatic.vcf

# Mutational signatures are obtained from COSMIC:
#   http://cancer.sanger.ac.uk/cosmic/signatures
mut-sig-file: resources/signatures_probabilities.txt

# The following list defines the relative contribution each signature (1-30).
# Signatures not present in the list will not be applied.
mut-signatures:
  'Signature 1': 1.0

#-------------------------------#
#      sampling parameters      #
#-------------------------------#

# sampling matrix (samples x clones)
# row sums must be <= 1.0
# if < 1.0, the difference to 1.0 is interpreted as normal cell contamination
# first column contains sample name (used to name output files)
# NOTE: make sure number of columns correspond to "clones" parameter +1
samples:
  ## only generate healthy reads:
  #- [ sample1 ]
  ## 3x5 scheme
  #- [ sample1, 0.2, 0.2, 0.1, 0.15, 0.25 ]
  #- [ sample2, 0.1, 0.0, 0.3, 0.25, 0.15 ]
  #- [ sample3, 0.0, 0.4, 0.0, 0.00, 0.3  ]
  ## 3x4 scheme
  - [ sample1, 0.4, 0.0, 0.2, 0.2 ]
  - [ sample2, 0.7, 0.0, 0.0, 0.0 ]
  - [ sample3, 0.0, 0.4, 0.4, 0.0 ]

#-------------------------------#
#     sequencing parameters     #
#-------------------------------#

# haploid depth of coverage
seq-coverage      : 50
# read length
seq-read-len      : 100
# mean fragment length (only for paired-end reads)
seq-frag-len-mean : 500
# standard deviation of fragment length (only for paired-end reads)
seq-frag-len-sd   : 20
# path to ART executable
seq-art-path      : /home/harry/src/art_src_MountRainier_Linux/art_illumina
# whether to use reads from healthy sample for tumor samples
seq-reuse-reads   : true
...
