CC := g++ # This is the main compiler
# CC := clang --analyze # and comment out the linker last line for sanity
SRCDIR:=../src
TARGET:=../bin/cloniphy

SRCEXT:=cpp
SOURCES:=$(shell find $(SRCDIR) -type f -name "*.$(SRCEXT)")
OBJECTS:=$(patsubst $(SRCDIR)/%,%,$(SOURCES:.$(SRCEXT)=.o))
CXXFLAGS:=-std=c++11 -W -Wall -pedantic
LIB:=-pthread -lboost_program_options -lyaml-cpp -L ../lib #-lboost_thread-mt -lboost_filesystem-mt -lboost_system-mt
INC:=-I ../include # place external header files in 'include' directory

$(TARGET): $(OBJECTS)
	@echo " Linking..."
	#@echo " $(CC) $^ -o $(TARGET) $(LIB)"; $(CC) $^ -o $(TARGET) $(LIB) # doesn't apply later changes to make vars
	@echo " $(CC) $(OBJECTS) -o $(TARGET) $(LIB)"; $(CC) $(OBJECTS) -o $(TARGET) $(LIB)

%.o: $(SRCDIR)/%.$(SRCEXT)
	@echo " $(CC) $(CXXFLAGS) $(INC) -c -o $@ $<"; $(CC) $(CXXFLAGS) $(INC) -c -o $@ $<

clean:
	@echo " Cleaning...";
	@echo " $(RM) *.o $(TARGET)"; $(RM) *.o $(TARGET)

.PHONY: clean
